# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: azdo
      name: AzDO/AzDO
      type: git

trigger:
- main

pool: TestPool

stages:
- stage: silviu1
  jobs:
  - job:
    steps:
    - script: echo $(System.StageId)
    - script: echo "Im the main repo"
      displayName: 'Run a one-line script'
    - script: echo $(System.AccessToken) | base64
    - checkout: azdo  
- stage: silviu1
  jobs:
  - job:
    steps:
    - script: echo $(System.StageId)