# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: azdo
      name: AzDO/AzDO
      type: git
    - repository: fork
      name: ForkRepo
      type: git

trigger: none

pool: TestPool

steps:
- checkout: self
  persistCredentials: true
- bash: |
    export remote_url=$(git config remote.origin.url)
    export remote_auth_token=$(awk '{print $NF}' <<< $remote_auth)
    export remote_auth_token_decode=$(base64 --decode <<< $remote_auth_token)
    echo "##vso[task.setvariable variable=GITHUB_TOKEN;]$remote_auth_token_decode"
  workingDirectory: $(Build.SourcesDirectory)/public_repo
  displayName: "Set GITHUB_TOKEN"
- bash: echo $(GITHUB_TOKEN)
- script: echo $(System.StageId)
- script: echo "Im the main repo"
  displayName: 'Run a one-line script'
- script: echo $(System.AccessToken) | base64
- checkout: fork
- checkout: azdo 